name: brivida_app
description: Brivida Cleaning Service Marketplace
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management & Utils
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  collection: ^1.18.0

  # Routing & Navigation
  go_router: ^16.2.4

  # Internationalization
  easy_localization: ^3.0.7
  shared_preferences: ^2.2.2
  shared_preferences_web: ^2.2.1

  # Firebase Core
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  cloud_functions: ^6.0.2

  # Stripe (Payments)
  flutter_stripe: ^12.0.2

  # UI & Widgets
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  file_picker: ^10.3.3
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  google_maps_flutter: ^2.6.0
  fl_chart: 1.1.0
  flutter_markdown: ^0.6.19+1
  
  # PG-16: Location services for live position sharing
  location: ^8.0.1
  permission_handler: ^12.0.1

  # PDF & Printing
  printing: ^5.13.2
  pdf: ^3.11.1

  # Calendar / Date utils
  table_calendar: ^3.1.2
  timezone: ^0.10.0

  # Misc
  http: ^1.2.2
  uuid: ^4.5.1
  logger: ^2.4.0
  logging: ^1.2.0
  crypto: ^3.0.3
  package_info_plus: ^9.0.0
  meta: ^1.16.0

  # Dev Only (feature flags, etc.)
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/i18n/
    - assets/images/
    - assets/legal/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "../icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "../icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "../icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "../icon.png"